import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency, formatDate } from '@/lib/utils';

interface InvoiceItem {
  productName: string;
  quantity: number;
  unitPrice: number;
  discount?: number;
  tax?: number;
  total: number;
}

interface InvoiceData {
  invoiceNumber: string;
  date: string;
  customerName: string;
  items: InvoiceItem[];
  subtotal: number;
  totalDiscount: number;
  totalTax: number;
  totalAmount: number;
  paymentMethod: string;
  paymentStatus: string;
}

export function generateInvoicePDF(invoice: InvoiceData): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header gradient bar
  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, pageWidth, 40, 'F');

  // Company name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('BillManager', 14, 22);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Inventory & Billing System', 14, 32);

  // Invoice label
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', pageWidth - 14, 22, { align: 'right' });
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.invoiceNumber, pageWidth - 14, 32, { align: 'right' });

  // Reset text color
  doc.setTextColor(30, 41, 59);

  // Invoice details
  const yStart = 55;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Bill To:', 14, yStart);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.customerName, 14, yStart + 7);

  doc.setFont('helvetica', 'bold');
  doc.text('Date:', pageWidth - 60, yStart);
  doc.setFont('helvetica', 'normal');
  doc.text(formatDate(invoice.date, 'long'), pageWidth - 60, yStart + 7);

  doc.text(`Payment: ${invoice.paymentMethod.replace('_', ' ').toUpperCase()}`, pageWidth - 60, yStart + 14);
  doc.text(`Status: ${invoice.paymentStatus.toUpperCase()}`, pageWidth - 60, yStart + 21);

  // Items table
  autoTable(doc, {
    startY: yStart + 30,
    head: [['#', 'Product', 'Qty', 'Unit Price', 'Discount', 'Tax', 'Total']],
    body: invoice.items.map((item, i) => [
      String(i + 1),
      item.productName,
      String(item.quantity),
      formatCurrency(item.unitPrice),
      formatCurrency(item.discount || 0),
      formatCurrency(item.tax || 0),
      formatCurrency(item.total),
    ]),
    theme: 'grid',
    headStyles: {
      fillColor: [99, 102, 241],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 9,
    },
    bodyStyles: { fontSize: 9, textColor: [30, 41, 59] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { cellWidth: 12 },
      2: { halign: 'center' },
      3: { halign: 'right' },
      4: { halign: 'right' },
      5: { halign: 'right' },
      6: { halign: 'right' },
    },
  });

  // Summary
  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  const summaryX = pageWidth - 80;

  doc.setFontSize(10);
  doc.text('Subtotal:', summaryX, finalY);
  doc.text(formatCurrency(invoice.subtotal), pageWidth - 14, finalY, { align: 'right' });

  doc.text('Discount:', summaryX, finalY + 7);
  doc.setTextColor(220, 38, 38);
  doc.text(`-${formatCurrency(invoice.totalDiscount)}`, pageWidth - 14, finalY + 7, { align: 'right' });

  doc.setTextColor(30, 41, 59);
  doc.text('Tax:', summaryX, finalY + 14);
  doc.text(formatCurrency(invoice.totalTax), pageWidth - 14, finalY + 14, { align: 'right' });

  // Total line
  doc.setDrawColor(99, 102, 241);
  doc.setLineWidth(0.5);
  doc.line(summaryX, finalY + 19, pageWidth - 14, finalY + 19);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Total:', summaryX, finalY + 28);
  doc.setTextColor(99, 102, 241);
  doc.text(formatCurrency(invoice.totalAmount), pageWidth - 14, finalY + 28, { align: 'right' });

  // Footer
  doc.setTextColor(148, 163, 184);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Thank you for your business!', pageWidth / 2, doc.internal.pageSize.getHeight() - 20, { align: 'center' });
  doc.text('Generated by BillManager', pageWidth / 2, doc.internal.pageSize.getHeight() - 14, { align: 'center' });

  return doc;
}

export function downloadInvoicePDF(invoice: InvoiceData) {
  const doc = generateInvoicePDF(invoice);
  doc.save(`${invoice.invoiceNumber}.pdf`);
}

export function printInvoicePDF(invoice: InvoiceData) {
  const doc = generateInvoicePDF(invoice);
  const blobUrl = doc.output('bloburl');
  window.open(blobUrl as unknown as string, '_blank');
}
